fix(build): Patch libbpf build with -mno-outline-atomics
The upstream libscap library that we build here using CMake contains an
embedded build of libbpf that is invoked using `make`. There are no
provisions for modifying the arguments to this `make` invocation from
the outside, hence we've already been patching the `cmake/modules/
libbpf.cmake` file in our `build.rs` script to make it use our compiler
wrapper and enable parallel builds.

While trying to build Edera natively on aarch64 Linux, I have stumbled
across another build issue affecting MUSL builds on this architecture
specifically [1].

```
...(libbpf.o): in function `gen_kprobe_legacy_event_name':
.../libbpf.c:10496:...: undefined reference to `__aarch64_ldadd4_sync'
          collect2: error: ld returned 1 exit status
```

It seems that the GCC compiler in use here enables `-moutline-atomics`
by default, which adds a dependency on libgcc. In our case, we link with
the MUSL libc, which does not provide these functions.

Pass `-mno-outline-atomics` in `EXTRA_CFLAGS` to avoid the issue. This
flag is specific to aarch64 and not valid for x86, so gate it
appropriately.

Part-of: https://linear.app/edera/issue/COR-95

Signed-off-by: Simon Veith <simon@edera.dev>

[1]: https://linear.app/edera/issue/COR-95